// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"songdb/pkg/controller"
	"songdb/pkg/routes"
	"songdb/pkg/service"
)

// Injectors from wire.go:

func InitializeSongRoutes(db *gorm.DB) routes.SongRoutes {
	songService := service.NewSongService(db)
	songController := controller.NewSongController(songService)
	songRoutes := routes.NewSongRoutes(songController)
	return songRoutes
}

func InitializeAlbumRoutes(db *gorm.DB) routes.AlbumRoutes {
	albumService := service.NewAlbumService(db)
	albumController := controller.NewAlbumController(albumService)
	albumRoutes := routes.NewAlbumRoutes(albumController)
	return albumRoutes
}

func InitializeSongRelRoutes(db *gorm.DB) routes.SongRelRoutes {
	songRelService := service.NewSongRelService(db)
	songRelController := controller.NewSongRelController(songRelService)
	songRelRoutes := routes.NewSongRelRoutes(songRelController)
	return songRelRoutes
}
